### PR TITLE
Add explore page.

### PR DESCRIPTION
**Pull request by mayacopeland**
Begin the work on the "Explore" page. 

Implements the 'explore' page as per #17

This does not add
- Starring
- Forking
- Issues
- Last updated
Could be added in the future, therefore has been left with a default value of 0 until the values exist within the database.

Attached are some examples of if an instance has no repositories or some repositories.

Some changes are likely to be needed as Fomatic UI tables can play weird.

image
image

### CODE REVIEW

**Comment by mayacopeland** [comment]
It turns out, in my original commit, the offset very likely wouldn't have went on forever, but because of your suggestion I've removed the need for offsets and whatnot.

I'm not sure how popular this could be, but the database requests for the explore page turn into an API endpoint, which would allow for searching instead of CTRL+F.

**Comment by mellowagain** [comment]
Thank you for your contribution and your work. I more had infinite scrolling with partial templating in mind instead of just fetching every single repository. Thanks to our usage of htmx in the project already, it should be relatively easy, as you can see in the [commit list example](https://github.com/mellowagain/gitarena/blob/41efc28/templates/html/repo/commit_list_component.html#L14-L18).

This can be achieved like this:

1. Create a second sub-template that only renders the repositories and include that in the main template
2. On the explore route render the full template or only the partial template [based on whenever it was a htmx request](https://github.com/mellowagain/gitarena/blob/41efc28/src/routes/repository/commits.rs#L88-L91) or not 

If you need any more help, feel free to reach out either here on the issue or privately. Here are a few more documentation links that may help you out:

* [Htmx infinite scroll example](https://htmx.org/examples/infinite-scroll/)
* [Tera template includes](https://tera.netlify.app/docs/#include)

**Comment by mayacopeland** [comment]
@mellowagain Can you check this on your local instance? As, for whatever reason, I was unable to register on my own local instance.

I'm not confident in how I've made this look due to my inability to test.

**Comment by mellowagain** [comment]
Hey, yea I have checked it out and the template is erroring, as `is_last_iter` is not defined. 

I have also noticed that you do not check for view access for the repository, meaning that if the repository is for example private or internal, it can be viewed from this page without authorization. Please check if the current authenticated `WebUser` is allowed to view the specific repository (`privilege::check_access`). You can see an example [here](https://github.com/mellowagain/gitarena/blob/6665912/src/routes/repository/git/git_receive_pack.rs#L64-L66).

**Comment by mayacopeland** [comment]
Is it possible to send one of these functions to Tera, or should I remove these results from the list?

From looking at the docs I'm not sure if the former is possible.

**Comment by mellowagain** [comment]
The problem is that the access functions take a `Executor` (= they require database access). Tera does not dependency inject one, which makes it impossible to make a custom `Test`. You'd have to go filter them out before sending the result to Tera to render the template.

**Comment by mellowagain** [comment]
In the meantime starring has been added to GitArena in 89e4d00. Now you should be able to easily show that star amount instead of showing a dummy number.

I suggest you get the star count via Ajax on the client side after the template has been rendered but you can also receive the star count directly in the request handler and send it into the template directly.

**Comment by mayacopeland** [comment]
closing until further notice

**Pull request closed without merging**
